get_feature_shares <- function(features) {
  
  ret <- data.frame(chars_per_word = (features$no_of_chars / features$no_of_words),
                    chars_per_word_remainder = (features$no_of_chars_remainder / features$no_of_words_remainder),
                    chars_per_word_title = (features$no_of_chars_title_only / features$no_of_words_title_only),
                    words_per_sents = (features$no_of_words / features$no_of_sentences),
                    verbs_per_words = (features$no_of_verbs / features$no_of_words),
                    interjections_per_words = (features$no_of_interjections / features$no_of_words),
                    adjectives_per_words = (features$no_of_adjectives / features$no_of_words),
                    adverbs_per_words = (features$no_of_adverbs / features$no_of_words),
                    commas_per_words = (features$no_of_commas / features$no_of_words),
                    common_words_per_words = (features$no_of_common_words / features$no_of_words),
                    dependents_per_words = (features$no_of_dependents / features$no_of_words),
                    exclamations_per_words = (features$no_of_exclamation_marks / features$no_of_words),
                    foreign_words_per_words = (features$no_of_foreign_words / features$no_of_words),
                    gerunds_per_words = (features$no_of_gerunds / features$no_of_words),
                    non_poetry_per_words = (features$no_of_non_poetry_words / features$no_of_words),
                    non_poetry_100_per_words = (features$no_of_non_poetry_words_share100 / features$no_of_words),
                    non_poetry_50_per_words = (features$no_of_non_poetry_words_share50 / features$no_of_words),
                    poetry_100_per_words = (features$no_of_poetry_words_share100 / features$no_of_words),
                    poetry_50_per_words = (features$no_of_poetry_words_share50 / features$no_of_words),
                    poetry_per_words = (features$no_of_poetry_words / features$no_of_words),
                    pronouns_per_words = (features$no_of_pronouns / features$no_of_words),
                    propers_per_words = (features$no_of_proper_nouns / features$no_of_words),
                    questions_per_words = (features$no_of_question_marks / features$no_of_words),
                    roots_per_words = (features$no_of_root / features$no_of_words),
                    verbs_per_words = (features$no_of_verbs / features$no_of_words),
                    verbs_per_words = (features$no_of_verbs_past / features$no_of_words),
                    inflected_per_words = (features$x_no_of_inflected_words / features$no_of_words),
                    antique_per_words = (features$no_of_antique_names / features$no_of_words),
                    root_of_index_in_sentence = features$root_of_index_in_sentence,
                    root_offset_chars = features$root_offset_characters,
                    features$len_words,
                    author_age=features$author_age,
                    pagecount = features$pagecount,
                    physical_extent = features$physical_extent,
                    publication_year = features$publication_year,
                    first_3_pos = features$first_3,
                    last_3_pos = features$last_3,
                    first_pos = features$first_1,
                    last_pos = features$last_1,
                    is_poetry = features$is_poetry
  )}
